### ISSUE TITLE
stress test: redundant msg "appending --bloom-bits.."

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#193]
when running the stress test with filter uri, the CreateFilterPolicy method prints to stderr when bloom_bits > 0 the normal behavior:
"note: appending --bloom-bits (%f) to --filter-uri" 
this is not an error and im not sure what the reason for this print is.

**Comment by isaac-io** [comment]
This isn't a bug, and it's indeed not an error. It's simply printed to `stderr` in order to make sure that it's not missed because this behaviour isn't intuitive and can be frustrating to debug in the error case. Mark was actually against printing this notification, but as @erez-speedb 's experience shows, this is something that users may encounter in the wild (quoting his message from Slack):

>I found a problem, not sure if its by design.
> When specifying both filter uri and bloom bits, the db_bench try to concatenate the bits
> E.g
> ```
> -bloom_bits=10 -filter_uri=speedb.PairedBloomFilter:20 
> ```
> Resulted with error
> ```
> failure creating filter policy[speedb.PairedBloomFilter:20:10.000000
> ```

**Comment by Yuval-Ariel** [comment]
in the stress test, by design theres an option to set the bloom bits of the filter policy with uri either with : or by passing a bloom bits flag greater than 0. i think a better way of handling this case would be to simply fail the user if the params are not correctly specified instead of the current solution.

**Comment by isaac-io** [comment]
The reason for this is that the default in `db_stress` is to have `-bloom_bits=10`, so even if the user didn't pass anything it would take effect (this is in contrast to `db_bench` where the default is `-1`), so even if we fail when both the URI and the`bloom_bits` are combined, it's not clear to the user how to solve this (that's actually how we did it initially, and then @udi-speedb stumbled upon it and was confused because it's not clear that you need to pass `-1` to `-bloom_bits` in order for the URI configuration to take effect). So automatically appending while printing this notification was a compromise, but by no means the best option out there, so I'm open to ideas for solving this without breaking existing behaviour (i.e. setting `bloom_bits` to -1 in `db_stress` by default as in `db_bench` is a breaking change that would cause the Bloom filter to get less coverage, so it's not really a good option)

**Comment by Yuval-Ariel** [comment]
my approach would be to fail during initialization if theres misconfiguration and inform the user how to properly configure it

**Comment by isaac-io** [comment]
The failure in any case would not extend beyond initialisation. The problem is that when we fail to construct a filter based on URI, we have no way to tell why. For example, in case you provide a filter URI of `spdb.PairedBloomFilter:10` with `bloom_bits=-1`, you'll still get an error which is the exact same as the one that Erez got:

> ```
> failure creating filter policy[spdb.PairedBloomFilter:10
> ```

And unfortunately it would be the same error with the URI set to only `spdb.PairedBloomFilter` and `bloom_bits=10`, because when URI construction fails, we don't have any information why it failed, so we can't tell the user how to fix it.
