### ISSUE TITLE
Speedb Artifacts

### ISSUE THREAD

**Issue by bosmatt** [speedb-io/speedb#64]
- Artifacts from a Speedb build (JAR, Libraries, etc) will include the Speedb name (e.g. libspeedb.a)
- Installation packages (CMake packages, Maven artifactory, apt/yum installers, etc) will include "Speedb"
- The Usage/Version of the library and executables will refer to Speedb

**Comment by isaac-io** [comment]
For the Makefile build artefact names were the only thing that changed, so the build is exactly the same as it was:
* For a static library: `make clean && DEBUG_LEVEL=0 make -j16 static_lib` should create a file named `libspeedb.a`
* For a shared library: `make clean && DEBUG_LEVEL=0 LIB_MODE=shared make -j16 shared_lib` should create files named `libspeedb.so*` with the Speedb version attached (i.e. `libspeedb.so.2.0.0` instead of `librocksdb.so.7.2.2`).
* For the Jar: `make jclean && DEBUG_LEVEL=0 make -j16 rocksdbjavastatic` should create both `libspeedbjni-linux64.so` and `speedbjni-2.0.0-linux64.jar` under `java/target`.
* Otherwise everything should be the same as before, except for the `rocksdb_dump` and `rocksdb_undump` which have been renamed `speedb_dump` and `speedb_undump` respectively.

For the CMake build the package name has been changed from `RocksDB::rocksdb` to `Speedb::speedb` and unfortunately target names also needed to change:
* For a static library: `rm -rf build && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j16 speedb` should create a file named `libspeedb.a`
* For a shared library: `rm -rf build && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j16 speedb-shared` should create files named `libspeedb.so*` with the Speedb version attached (i.e. `libspeedb.so.2.0.0` instead of `librocksdb.so.7.2.2`).
* For the Jar: `rm -rf build && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j16 speedbjni` should create both `libspeedbjni.so` and `speedbjni_classes.jar` under `java`.
* Otherwise here too everything should be the same as before, except for the `rocksdb_dump` and `rocksdb_undump` which have been renamed `speedb_dump` and `speedb_undump` respectively.

For both types of builds, the various tools (`db_bench`, `db_stress`, `ldb`, etc.) should now print Speedb instead of RocksDB and use the Speedb version information instead of the RocksDB one. Also, this has already been the case, but the LOG files generated during runs in the database directory should have Speedb in it instead of RocksDB.
