### ISSUE TITLE
speedb filter conflict with speedb pinning.

### ISSUE THREAD

**Issue by erez-speedb** [speedb-io/speedb#675]
Below are the results on 3GB cache size
https://admin.speedb.io/performance?items=wWC407gvcyxah2dfUkrc&items=2s3UvTP8W41VmmeWrwsC&items=moOyUeoY2nZIbytEOGlD&items=HregIvxzRjOWDOxKZG0R&items=maSAZKq2KU8GyHskPyY9&colors=%23F06292&colors=%23BA68C8&colors=%239575CD&colors=%237986CB&colors=%2364B5F6
The best two are manual pinning and enable speedb on bloom filter
The bad are no filter and enable speedb with speedb filter.

**Comment by RoyBenMoshe** [comment]
Further investigation concluded that there was no conflict and the problem was due to the mid_precent and bottom_percent values in the enable test.
[https://admin.speedb.io/performance?items=hGNXsDgTosQOHxVs1pXk&items=ymFnz5ZJWXvM4Ng[…]gbYsLY9dvn&colors=%23F06292&colors=%23BA68C8&colors=%239575CD](https://admin.speedb.io/performance?items=hGNXsDgTosQOHxVs1pXk&items=ymFnz5ZJWXvM4NggP4AZ&items=lrgZSvYWlwgbYsLY9dvn&colors=%23F06292&colors=%23BA68C8&colors=%239575CD)
